volumes:
  core_local_postgres_data: {}
  core_local_postgres_data_backups: {}
  core_local_redis_data: {}
  media: {}
  static: {}

services:
  django: &django
    build:
      context: ./server
      dockerfile: ./compose/local/django/Dockerfile
    image: core_local_django
    container_name: core_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - ./server:/app:z
    env_file:
      - ./server/.envs/.local/.django
      - ./server/.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: ./server
      dockerfile: ./compose/production/postgres/Dockerfile
    image: core_production_postgres
    container_name: core_local_postgres
    volumes:
      - core_local_postgres_data:/var/lib/postgresql/data
      - core_local_postgres_data_backups:/backups
    env_file:
      - ./server/.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: core_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: core_local_redis

    volumes:
      - core_local_redis_data:/data

  celeryworker:
    <<: *django
    image: core_local_celeryworker
    container_name: core_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: core_local_celerybeat
    container_name: core_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: core_local_flower
    container_name: core_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  taxi-client:
    build:
      context: ./client
    command: npm install && ng serve --host 0.0.0.0
    container_name: taxi-client
    depends_on:
      - django
    environment:
      - CHROME_BIN=chromium-browser
    ports:
      - 4201:4200
    volumes:
      - ./client:/usr/src/app

  nginx:
    build:
      context: ./nginx
    container_name: taxi-nginx
    depends_on:
      - django
      - taxi-client
    ports:
      - 8080:80
    restart: always
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static
